### ISSUE TITLE
the BottomEdgeHint as no text neither an Icon

### ISSUE THREAD

**Issue by mymike00** [bhdouglass/dice-roller#1]
the BottomEdgeHint hasn't a text neither an icon so it's all white.
setting them would be nicer
![photo_2017-11-19_18-19-24](https://user-images.githubusercontent.com/28359593/32993288-34109118-cd56-11e7-8db5-564717c6abff.jpg)

**Comment by bhdouglass** [comment]
Normally this just shows as a little grey "up" icon. What shows up for your core apps?

**Comment by mymike00** [comment]
I mean while dragging the BottomEdge up
this one https://docs.ubuntu.com/phone/en/apps/design/building-blocks/bottom-edge#hint-2

**Comment by bhdouglass** [comment]
Ohhhh, gotcha, I'll get that fixed asap. Thanks!

**Comment by bhdouglass** [comment]
Fixed in v2.31!
